
# Configurações do servidor
server:
  port: 8080

database: h2

# Configurações do banco de dados
spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
  sql:
    init:
      schema-locations: classpath*:db/${database}/schema.sql
      data-locations: classpath*:db/${database}/data.sql

# Configurações do logging
logging:
  level:
    root: info
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure.jdbc.DataSourceInitializer: DEBUG